// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eaglsvgnqzoisvbpjpgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhZ2xzdmducXpvaXN2YnBqcGdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NzE0MzQsImV4cCI6MjA1MTE0NzQzNH0.AIRG54MzU9GeFwISc8CT6xOxxu61ZxzR0TTnIYRnsqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);